name: Push All Files

on:
  push:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set Git identity
        run: |
          git config --global user.email "eng21ct0007@dsu.edu.in"
          git config --global user.name "hrk-2109"
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Bandit Scan
        run: |
         pip install bandit
         bandit -r . -l -i -c bandit.yaml || true

  zap_scan:
    runs-on: ubuntu-latest
    name: zap_scan
    needs: bandit_scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.HTOKEN }}
          target: 'https://techtidy.github.io/my-app-dev/'
          cmd_options: '-a'
  copy-all-files:
    needs: [bandit_scan, zap_scan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: README
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{secrets.HTOKEN }}
        with:
          source_file: 'README.md'
          destination_repo: 'Techtidy/my-appp-test'
          user_email: 'eng21ct0007@dsu.edu.in'
          user_name: 'hrk-2109'

      - name: src
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{secrets.HTOKEN }}
        with:
          source_file: 'src/'
          destination_repo: 'Techtidy/my-appp-test'
          user_email: 'eng21ct0007@dsu.edu.in'
          user_name: 'hrk-2109'

      - name: readme
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{secrets.HTOKEN }}
        with:
          source_file: 'README.md'
          destination_repo: 'Techtidy/my-appp-test'
          user_email: 'eng21ct0007@dsu.edu.in'
          user_name: 'hrk-2109'

      - name: security
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{secrets.HTOKEN }}
        with:
          source_file: 'security/'
          destination_repo: 'Techtidy/my-appp-test'
          user_email: 'eng21ct0007@dsu.edu.in'
          user_name: 'hrk-2109'

      - name: techtidy
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{secrets.HTOKEN }}
        with:
          source_file: 'TechTidy Website/'
          destination_repo: 'Techtidy/my-appp-test'
          user_email: 'eng21ct0007@dsu.edu.in'
          user_name: 'hrk-2109'

     
      
